### PR TITLE
Refactor build workflow

### PR DESCRIPTION
**Pull request by webbnh**
## Changes introduced with this PR

This PR refactors the `build.yaml` GitHub workflow:
- moves the `.github/scripts/gogenerate.sh` to the `arcaflow-reusable-workflows` repo;
- uses reusable workflows for linting, testing, and `go generate`;
- renames the workflow file to `.yaml` to be consistent with other repos;
- adds a trigger for `v*` tags;
- obtains the Go version from the `ARCALOT_GO_VERSION` instead of hard-coding it.

_Note:  this PR depends on https://github.com/arcalot/arcaflow-reusable-workflows/pull/21, so the CI won't run until that PR is merged (until such time, this PR will be a draft)._

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]
> (until such time, this PR will be a draft)

You neglected to act on that assertion, but in isolation this one looks fine. 😆

**Comment by webbnh** [comment]
> > (until such time, this PR will be a draft)
> 
> You neglected to act on that assertion, but in isolation this one looks fine. 😆

Weird:  I guess I clicked wrong on the warning dialog.  (It's a draft, _now_....  🙂)

**Review by jaredoconnell — APPROVED** [review]

**Comment by webbnh** [comment]
Marking this ready for review (although, it already has two approvals).  We just need to see the CI run (which, maybe, this comment will trigger).

**Comment by webbnh** [comment]
Aaaaand, we're back to draft mode while I figure out how to deal with the fact that the `gogenerate.sh` script invocation is not in the context that I thought (or hoped?) it was.

**Pull request merged**
